config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :recipe_type
  validates :title, :recipe_type, :cuisine, :difficulty,  :cook_time, :ingredients,  :cook_method, presence: true
  def cook_time_min
    "#{cook_time} minutos"
  end
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    @recipes_types = RecipeType.all
  end

  def create
        
    @recipe = Recipe.create(recipe_params)
    if @recipe.save      
    redirect_to  @recipe
    else
      @recipes_types = RecipeType.all
      render "new"
    end
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
    @recipes_types = RecipeType.all
  end

  def update
    
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      flash[:success] = 'Receita marcada como destaque com sucesso!'
      redirect_to @recipe
    else
      @recipes_types = RecipeType.all
      render "edit"
    end   

  end

  private
  #Os metodos abaixo do private serão tratados como metodos e não como actions

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id,
                                   :cuisine, :difficulty,
                                   :cook_time, :ingredients,
                                   :cook_method, :featured)    
  end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
    @featured_recipes = Recipe.where(featured: true)

    @another_recipes = Recipe.where(featured: false)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= render partial: "shared/errors", locals: {object: @recipe } %>

<%= form_for @recipe do |f| %>
  <%= f.label :title, "Título" %>
  <%= f.text_field :title %>

  <%= f.label :recipe_type_id, "Tipo da Receita" %>
  <%= f.collection_select(:recipe_type_id, @recipes_types, :id, :name)  %>

  <%= f.label :cuisine, "Cozinha" %>
  <%= f.text_field :cuisine %>

  <%= f.label :difficulty, "Dificuldade" %>
  <%= f.text_field :difficulty %>

  <%= f.label :cook_time, "Tempo de Preparo" %>
  <%= f.number_field :cook_time %>

  <%= f.label :ingredients, "Ingredientes" %>
  <%= f.text_area :ingredients %>

  <%= f.label :cook_method, "Como Preparar" %>
  <%= f.text_area :cook_method %>

  <%= f.label :featured, 'Destaque' %>
  <%= f.check_box :featured%>

  <%= f.submit "Enviar" %>
<% end %>

app/views/recipes/_recipe.html.erb
<h1><%= link_to recipe.title, recipe %></h1>
  <%if recipe.featured?%>
    <%= image_tag 'star.png' %>
  <%end%>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time_min %></li>  
 </ul>

app/views/recipes/edit.html.erb
<h1>Editar Receita</h1>

<%= render 'form' %>

app/views/recipes/new.html.erb
<h1>Nova Receita</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<% if @recipe.featured? %>
  <%= flash[:success] %>
  <%= image_tag 'star.png'%>
<% end %>

<h1><%= @recipe.title %></h1>

<h3>Detalhes</h3>
<p><%= @recipe.recipe_type.name %></p>
<p><%= @recipe.cuisine %></p>
<p><%= @recipe.difficulty %></p>
<p><%= @recipe.cook_time_min %></p>
<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>
<h3>Como Preparar</h3>
<p><%= @recipe.cook_method %></p>

<%= link_to "Editar", edit_recipe_path(@recipe), class: 'btn btn-primary' %>

<%= link_to "Voltar", root_path, class: "btn btn-secondary" %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <p>Você deve informar todos os dados da receita</p>
<% end %>

app/views/shared/_form.html.erb
<%= render partial: "shared/errors", locals: {object: @recipe } %>

<%= form_for @recipe do |f| %>
  <%= f.label :title, "Título" %>
  <%= f.text_field :title %>

  <%= f.label :recipe_type, "Tipo da Receita" %>
  <%= f.text_field :recipe_type %>

  <%= f.label :cuisine, "Cozinha" %>
  <%= f.text_field :cuisine %>

  <%= f.label :difficulty, "Dificuldade" %>
  <%= f.text_field :difficulty %>

  <%= f.label :cook_time, "Tempo de Preparo" %>
  <%= f.number_field :cook_time %>

  <%= f.label :ingredients, "Ingredientes" %>
  <%= f.text_area :ingredients %>

  <%= f.label :cook_method, "Como Preparar" %>
  <%= f.text_area :cook_method %>

  <%= f.submit "Enviar" %>
<% end %>

app/views/welcome/index.html.erb
<%= link_to "Home", root_path, class: 'nav-link' %>
<%= link_to "Enviar uma receita", new_recipe_path, class: 'nav-link' %>

<h1>CookBook</h1>
<p>Bem-vindo ao maior livro de receitas online</p>


<div id='recipes-featured'>
<h3>Receitas destaque</h3>
<!-- Convencao ao extremo
<%= render @featured_recipes %> -->

<% @featured_recipes.each do |r| %>
  <%= render r %>
<% end %>

</div>

<div id='other-recipes'>
<h3>Outras receitas</h3>
<% @another_recipes.each do |r| %>
  <%= render r %>
<% end %>

</div>